# -*- coding: utf-8 -*-
"""milestone3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yqUUm4nTzadE0uxgviFeyD28LMiq07W

## Milestone 3
### Feature Engineering
### Yiscah Mark
"""

from google.colab import files

uploaded = files.upload()

"""Displaying the data. Throughout I keep displaying the first five rows to see the changes."""

# Import necessary libraries
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
display(df.head())

"""Checking the shape, the datatype in each column, the column names..."""

# Check the initial shape and info
print(df.shape)
df.head()
df.info()
df.describe()
df.isna()

"""When I counted the fuel types in the fuel column some of the petrol fuel were spelled with a capital P and some with a lowercase p, therefore I standardized the text to lowercase. I also reprinted the revised totals and I see that the electric and lpg have such low counts that it just acts as noise."""

# 1. Standardize the text to lowercase BEFORE encoding
df['fuel'] = df['fuel'].str.lower()

# 2. Re-run the encoding
# We will also drop 'electric' manually or let it be handled by drop_first
df = pd.get_dummies(df, columns=['fuel'], drop_first=True, dtype=int)

# 3. Check the counts again
fuel_cols = [col for col in df.columns if col.startswith('fuel')]
print(df[fuel_cols].sum())

"""I removed the electric and LPG columns, and then rechecked the new totals.

"""

# Filter the dataframe to keep only Diesel and Petrol based on dummy variables
# This removes the 1 Electric and 23 LPG rows
# Keep rows where fuel_electric is 0 AND fuel_lpg is 0.
df = df[(df['fuel_electric'] == 0) & (df['fuel_lpg'] == 0)]

# The original 'fuel' column no longer exists, so standardizing casing is not applicable.
# Verify the clean counts by summing the dummy variables
print("Remaining fuel type counts:")
print(f"Diesel: {df['fuel_diesel'].sum()}")
print(f"Petrol: {df['fuel_petrol'].sum()}")
print(f"Electric: {df['fuel_electric'].sum()}")
print(f"LPG: {df['fuel_lpg'].sum()}")

display(df.head())

"""There are too many unique names of cars. This is too noizy for the model. The company is enough to get a picture and predict. I rewrote a new name column wich just pulls out the first word of each name, which is the company.

I then printed all teh unique names.
"""

# Extract the first word from the 'name' column and reassign it to replace the original
df['name'] = df['name'].str.split().str[0]

# Verify the change
print(df['name'].unique())
display(df.head())

"""Here I printed the unique car company names along with the counts."""

print("Number of unique car brands:", df['name'].nunique())
print("car brands:\n", df['name'].value_counts().head(29))

"""Some conpanies appear very rearly. In a way they act as noise and mess up the model. On the other hand we lose information. I decided to put the threshold at 10. Any car company that appears less that 10 times is removed."""

# Get the counts of each car brand
brand_counts = df['name'].value_counts()

# Identify brands with less than 10 occurrences
rare_brands = brand_counts[brand_counts < 10].index

# Filter the DataFrame to keep only brands with 10 or more occurrences
df = df[~df['name'].isin(rare_brands)]

print(f"Number of car brands before filtering: {len(brand_counts)}")
print(f"Number of car brands after filtering: {df['name'].nunique()}")
print("Remaining car brands (top 20):\n", df['name'].value_counts().head(20))

display(df.head())

"""I have two numerical columns (year and Kilometers driven). The year only goes to about two thousand and the kilometers goes over 100,000. Since these ranges are so different it can mess up the model. In the next cell I will normalize the figures by making each a number between 0 and 1 so the difference in range doesn't skew everything.I used the min-max scaling in which 0 is the lowest number in ther range and 1 is the highest. I didn't use standard scaling, which scales relative the the standard deviations because i wanted it to be in the same range as the encodded columns.

I am obviously not normalizing my selling price column because it is the target variable.
"""

from sklearn.preprocessing import MinMaxScaler

# Initialize the scaler
scaler = MinMaxScaler()

# Select the columns to normalize
cols_to_fix = ['km_driven', 'year']

# Apply the transformation
df[cols_to_fix] = scaler.fit_transform(df[cols_to_fix])

display(df.head())

"""I am encoding these categoricl tada columns so i can feed it into a regression model."""

categorical_cols_to_encode = ['seller_type', 'transmission', 'owner']

# Apply one-hot encoding
df = pd.get_dummies(df, columns=categorical_cols_to_encode, drop_first=True, dtype=int)

display(df.head())
print(f"Shape after encoding: {df.shape}")

"""I am examining the rest of the encoded categories to see if I should drop anything."""

print("Current columns in DataFrame:")
print(df.columns.tolist())

print("\n--- Examining Categorical Feature Distributions (after one-hot encoding) ---")

# Assuming these columns were one-hot encoded with drop_first=True
# We'll sum the dummy variables to get a sense of their distribution.

# Seller Type
seller_type_dummies = [col for col in df.columns if col.startswith('seller_type_')]
if seller_type_dummies:
    print("\nSeller Type Distribution (from dummy variables):")
    display(df[seller_type_dummies].sum().rename(lambda x: x.replace('seller_type_', '')))
else:
    print("\nNo seller_type dummy columns found. Please verify preprocessing steps.")

# Transmission Type
transmission_dummies = [col for col in df.columns if col.startswith('transmission_')]
if transmission_dummies:
    print("\nTransmission Type Distribution (from dummy variables):")
    display(df[transmission_dummies].sum().rename(lambda x: x.replace('transmission_', '')))
else:
    print("\nNo transmission_type dummy columns found. Please verify preprocessing steps.")

# Owner Type
owner_dummies = [col for col in df.columns if col.startswith('owner_')]
if owner_dummies:
    print("\nOwner Type Distribution (from dummy variables):")
    display(df[owner_dummies].sum().rename(lambda x: x.replace('owner_', '')))
else:
    print("\nNo owner_type dummy columns found. Please verify preprocessing steps.")

print("\nCar Brand (Name) Distribution (after rare brand removal):")
display(df['name'].value_counts())

"""Everything looks within range. I will leave it."""



"""Since most of the cars are priced regularly and we have a few ouliers that are totaly out of range, I will perform log transformation on my price column. This "shows" the model that predicting $5,000 off on a $25,000 car is a lot worse than oon a $100,000 car. The log transformation normalizes the selling price in this way."""

# Apply the log transformation
# df['price_log'] = np.log(df['selling_price'])

# Compare the skewness (Optional check)
# print(f"Original Skew: {df['selling_price'].skew()}") # This line will also cause an error if selling_price is dropped
print(f"Log-Transformed Skew: {df['price_log'].skew()}")

display(df.head())

"""I didn't want to one-hot encode the names column because I didn't like how so many names that mean something just became a series of ones and zeros. The only way to feed it to a regression model is if it is numerical so here it is."""

# Apply one-hot encoding to the 'name' column
df = pd.get_dummies(df, columns=['name'], drop_first=True, dtype=int)

display(df.head())
print(f"Shape after encoding 'name': {df.shape}")

"""I am dropping the original price column so we don't get confused."""

cols_to_drop = ['selling_price']

# Drop them permanently
df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

display(df.head())

"""I was going to make the kilometers driven into bins, like split into categories. I didn't since I normalized it and it works well as a continuous number.

This is the last step to prepare for regression, by splitting the features and the target variable into x and y.
"""

X = df.drop('price_log', axis=1)
y = df['price_log']

print("Shape of X (features):", X.shape)
print("Shape of y (target):", y.shape)

display(X.head())
display(y.head())